userNum = int(input('Enter integer: '))
print(userNum)
print('You entered:', userNum)
print(userNum, 'squared is', userNum*userNum)
print('And', userNum, 'cubed is', userNum*userNum*userNum, '!!')
anotheruserNum = int(input('Enter another integer:\n'))
print(userNum, '+', anotheruserNum, 'is', userNum+anotheruserNum)
print(userNum, '*', anotheruserNum, 'is', userNum*anotheruserNum)
